DROP DATABASE IF EXISTS Jsp_community;
CREATE DATABASE Jsp_community;
USE DATABASE Jsp_community;

CREATE TABLE article(
	id INT(100) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	updateDate DATETIME NOT NULL,
	title CHAR(200) NOT NULL,
	`body` LONGTEXT NOT NULL
);

SELECT * FROM article;

INSERT INTO article(regDate, updateDate, title, `body`)
VALUES (NOW(), NOW(), CONCAT("제목", RAND()), CONCAT("내용", RAND())
);


CREATE TABLE `member`(
	id INT(100) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	updateDate DATETIME NOT NULL,
	loginId CHAR(20) NOT NULL,
	loginPw CHAR(20) NOT NULL,
	`name` CHAR(20) NOT NULL
	);

SELECT * FROM `member`;

ALTER TABLE article ADD COLUMN memberId INT(10) UNSIGNED NOT NULL AFTER updateDate;

